[profile.default]
src = "src"
out = "out"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
libs = ["lib"]
remappings = [
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
  '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
]
via_ir = true
optimizer = true
optimizer_runs = 200