name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop
      - main

env:
  FOUNDRY_PROFILE: ci
  ETH_SEPOLIA_RPC_URL: ${{ secrets.ETH_SEPOLIA_RPC_URL }}
  SCROLL_SEPOLIA_RPC_URL: ${{ secrets.SCROLL_SEPOLIA_RPC_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  BACKEND_EOA: ${{ secrets.BACKEND_EOA }}
  BACKEND_PK: ${{ secrets.BACKEND_PK }}
  NFT_BASE_URI: https://dev.back.chatterpay.net/nft/metadata/opensea/
  FOUNDRY_DISABLE_NIGHTLY_WARNING: 1

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up cache for Foundry
        uses: actions/cache@v3
        with:
          path: |
            .forge-cache
            lib
          key: ${{ runner.os }}-forge-cache-${{ hashFiles('**/*.sol') }}

      - name: Initialize and update submodules
        run: git submodule update --init --recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: yarn test:local
        id: test
